field: e78aa919-66d6-4895-aba5-9e67c3c3a284 # Riders
fieldLayouts:
  48e1a9f1-9885-4933-b06f-b0e654471758:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a9e055e3-3a0f-4097-a01f-1b5291d48ff3 # Photo
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51378276-7439-483d-9fbb-7232808491ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 654340c6-51b6-475b-8a5c-7ee1fc41d725 # Full Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f80be96-322c-43bd-b060-1e6156ee5bf5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 005df6e8-38d3-4f00-81cf-3a755f6e7ee6 # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f428924-fdb2-40fd-ae1d-a9d472e4b7a2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 04a7ea6b-3d05-4f49-a9c7-ea92bc7d2f1f
        userCondition: null
fields:
  005df6e8-38d3-4f00-81cf-3a755f6e7ee6: # Description
    columnSuffix: zrobheoq
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  654340c6-51b6-475b-8a5c-7ee1fc41d725: # Full Name
    columnSuffix: vznbkjgz
    contentColumnType: text
    fieldGroup: null
    handle: fullName
    instructions: null
    name: 'Full Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a9e055e3-3a0f-4097-a01f-1b5291d48ff3: # Photo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: photo
    instructions: null
    name: Photo
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:be687ace-5f16-40ac-95e9-7591dda66d5a' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:be687ace-5f16-40ac-95e9-7591dda66d5a' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add a photo'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:be687ace-5f16-40ac-95e9-7591dda66d5a' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: rider
name: Rider
sortOrder: 1
