fieldLayouts:
  cf8cdf2b-ec13-4d82-a32e-e31057d8475b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: daa73310-3c33-4be1-bc35-fefead5c452c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 55088043-d90c-4b1b-a922-801cfe8d8e92
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
