columnSuffix: null
contentColumnType: string
fieldGroup: 631f6c4e-5561-49cf-9112-27cc005a4f48 # Home Page
handle: riders
instructions: null
name: Riders
searchable: false
settings:
  contentTable: '{{%matrixcontent_riders}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
