fieldLayouts:
  0c913f50-97ba-4195-b48c-19bc953bb94c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0a2ae81b-7399-4be2-916c-10d42107daa1 # Rich text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc2f9c93-fc33-48fe-ba2d-45c39183b7a1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a465e07e-f71e-4103-98bc-df5db801eed3
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
