defaultPlacement: end
enableVersioning: true
handle: generalPages
name: 'General Pages'
propagationMethod: all
siteSettings:
  145f1473-c721-4593-8740-4fceafa405d8: # Motoventure
    enabledByDefault: true
    hasUrls: true
    template: general.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: 1dc2afb6-a18a-4e58-aa35-10aa1fa142a1
type: structure
