defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  145f1473-c721-4593-8740-4fceafa405d8: # Motoventure
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
