defaultPlacement: end
enableVersioning: true
handle: stories
name: Stories
propagationMethod: all
siteSettings:
  145f1473-c721-4593-8740-4fceafa405d8: # Motoventure
    enabledByDefault: true
    hasUrls: true
    template: stories/_entry.twig
    uriFormat: 'stories/{slug}'
type: channel
